version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    healthcheck:
      test: pg_isready -U todo -d todo
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - todonet
  todo:
    image: todo
    hostname: todo
    build:
      context: todo
      target: prod
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GIN_MODE=release
      - PORT=8080
    healthcheck:
      test: curl http://localhost:8080/healthcheck
      interval: 10s
      timeout: 3s
      retries: 3
    expose:
      - "8080"
    networks:
      - todonet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      todo:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - todonet

networks:
  todonet:
